version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla
    volumes:
      - mysql_data:/var/lib/mysql

  joomla:
    image: joomla:latest
    container_name: joomla
    restart: always
    ports:
      - "8080:80"
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomla
      JOOMLA_DB_NAME: joomla
    depends_on:
      - mysql
    volumes:
      - joomla_data:/var/www/html

volumes:
  mysql_data:
  joomla_data:
